package it.polimi.ingsw.network;

public enum Type {
    HEARTBEAT,
    // from client
    UPDATE_CREATOR,
    UPDATE_AFTER_LOBBY_CRASH,
    UPDATE_AFTER_CONNECTION,
    SHOW_UPDATE_PLAYERS_IN_LOBBY,
    SHOW_UPDATE_PLAYER_STATUS,
    SHOW_UPDATE_COLOR,
    SHOW_UPDATE_OBJECTIVE_CARD,
    SHOW_UPDATE_AFTER_PLACE,
    SHOW_UPDATE_AFTER_DRAW,
    SHOW_UPDATE_CHAT,
    SHOW_UPDATE_CURRENT_PLAYER,
    SHOW_UPDATE_SUSPENDED_GAME,
    SHOW_WINNERS,
    ERROR,

    // from server
    FROM_SERVER,
    CONNECT,
    PLACE_STARTER,
    CHOOSE_COLOR,
    PLACE_OBJECTIVE,
    PLACE_CARD,
    DRAW,
    SEND_CHAT_MESSAGE,
    SET_PLAYER_NUMBER,
    DISCONNECT,
}
